adventure_game/adventure_game/urls.py
"""This module is used to route the urls to the views
"""

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('coreapp.urls', namespace="coreapp")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^adventure\d*/', include('map.urls', namespace="map")),
]

adventure_game/coreapp/urls.py
#pylint: disable=C0103
from django.conf.urls import url
from coreapp import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^auth/$', views.auth_view, name='auth'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.registration, name='registration'),
    url(r'^registration-submission/$', views.registration_submission, name='registrationSubmission'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^individual/$', views.individual, name="individual"),
    url(r'^story/$', views.story, name='story'),
    url(r'^add-family-member-submission/$', views.add_family_member_submission, name="addFamilySubmission"),
    url(r'^add-family-member/$', views.add_family_member, name="add-family-member"),
    url(r'^get_adventure_detail/$', views.get_adventure_detail, name='get_adventure_detail'),
    url(r'^adventureslist$', views.adventureslist, name="adventureslist"),
    url(r'^contact$', views.contact, name="contact"),
]

adventure_game/map/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.map, name='map'),
    url(r'^beginingstory$', views.beginingstory, name="beginingstory"),
    url(r'^task\d*$', views.task, name="task"),
    url(r'^missiontasksubmission$', views.mission_task_submission, name="missiontasksubmission"),
    url(r'^questionstasksubmission$', views.questions_task_submission, name="questionstasksubmission"),
    url(r'^save_current/$', views.save_current, name="save_current"),
    url(r'^special_game_json/$', views.special_game_json, name="special_game_json"),
    url(r'^visitorview$', views.visitorview, name="visitorview"),
]

adventure_game/map/models.py
from django.db import models
from django.contrib import auth
from django.contrib.auth.models import User
# Create your models here.


class Adventure(models.Model):
    """
    This holds our adventure game
    """
    adventure_id = models.CharField(unique=True, max_length=50, default='0000')
    adventure_name = models.CharField(max_length=200)
    adventure_description = models.TextField(max_length=2000, blank=True, default='')
    adventure_img_url = models.URLField(max_length=3000, blank=True, default='')
    theme_character_url = models.URLField(max_length=3000, blank=True, default='')

    adventure_category_choices = (
        ('Indoor', 'Indoor'),
        ('Outdoor', 'Outdoor'),
    )
    adventure_category = models.CharField(max_length=10, choices = adventure_category_choices, default='Outdoor')

    def __unicode__(self):
        return self.adventure_name


class Task(models.Model):
    """
    This holds the tasks of each adventure game.
    """
    adventure_name = models.ForeignKey(Adventure)
    task_num_choices = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    )
    task_number = models.CharField(max_length=10, choices = task_num_choices, default='1')
    task_type_choices = (
        ('Mission', 'Mission'),
        ('Questions', 'Questions'),
    )
    task_type = models.CharField(max_length=10, choices = task_type_choices, default='Mission')
    task_description = models.TextField(max_length=2000, blank=True, default='')
    task_detail = models.TextField(max_length=2000, blank=True, default='')
    place_img_url = models.URLField(max_length=3000, blank=True, default='')
    task_ans = models.CharField(max_length=2000, blank=True, default='')
    name_of_location = models.CharField(max_length=2000, blank=True, default='')
    id_of_task = models.CharField(max_length=200, blank=True, default='')
    google_map = models.URLField(max_length=3000, blank=True, default='')
    special_game = models.CharField(max_length=9000, blank=True, default='')
    def __unicode__(self):
        return self.task_number

class Question(models.Model):
    question_type_choices = (
        ('Math', 'Math'),
        ('English', 'English'),
        ('History', 'History'),
        ('Science', 'Science'),
    )
    question_type = models.CharField(max_length=10, choices = question_type_choices, default='Math')
    question_age_choices = (
        ('1. Pre-k', 'Pre-k'),
        ('2. Age 4-7', 'Age 4-7'),
        ('3. Age 8-10', 'Age 8-10'),    #index is for ordering
    )
    question_age = models.CharField(max_length=20, choices = question_age_choices, default='Pre-k')
    question_text = models.TextField(max_length=200, blank=True, default='')
    def __unicode__(self):
        return self.question_text

class Answer(models.Model):
    question_text = models.OneToOneField(Question)
    choice_1 = models.CharField(max_length=200, blank=True, default='')
    choice_2 = models.CharField(max_length=200, blank=True, default='')
    choice_3 = models.CharField(max_length=200, blank=True, default='')
    choice_4 = models.CharField(max_length=200, blank=True, default='')
    answer_choices = (
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', 'None from above'),
    )
    answer = models.CharField(max_length=10, choices = answer_choices, default='5')

    def __unicode__(self):
        return 'Q: '+str(self.question_text) + 'A: '+str(self.answer)


class adventures_info(models.Model):
    """
    This provides information about each adventure, e.g. Tools needed, expense.
    """
    adventure_name = models.OneToOneField(Adventure)
    items_needed = models.CharField(max_length=1000, blank=True, default='')
    expenses = models.CharField(max_length=1000, blank=True, default='')
    locations = models.CharField(max_length=2000, blank=True, default='')
    map_address = models.CharField(max_length=2000, blank=True, default='')

    def __unicode__(self):
        return 'items_needed: ' + self.items_needed + 'expenses: ' + self.expenses + 'locations: '+ self.locations

adventure_game/map/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.core.urlresolvers import reverse
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from .models import Adventure
from .models import Task
from .models import Question
from .models import Answer
from coreapp.models import Level_num
from coreapp.models import Track
from coreapp.models import Game_saved
from coreapp.models import current_adventures
from .models import adventures_info
import json

# Create your views here.

def map(request):
    """
    This is the map view, it collect a list of context and is pass along with
    map.html which renders entire map where users can see their adventures progress.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.

    Returns
    -------
    HttpResponseRedirectObject or HttpResponseObject
        It returns HttpResponseRedirectObject when user have not yet create a family member.
        It returns HttpResponseObject when user is logged in and have family member created.
    """
    user = request.user
    adventureid = request.GET.get('adventureid', '')
    if user.is_authenticated():
        if not user.character_set.all():
            messages.warning(request, 'Create your family roles so that you can start your adventures.')
            return HttpResponseRedirect(reverse('coreapp:profile'))
        else:
            if user.game_saved.adventure_saved:
                task_saved = str(user.game_saved.task_saved)
                adventure_saved = user.game_saved.adventure_saved
                adv = Adventure.objects.get(adventure_id = adventure_saved)
                tasks = Task.objects.filter(adventure_name = adv).order_by("id")
                task_list = []
                for task in tasks:
                    task_list_context = {
                        "id_of_task": task.id_of_task,
                        "place_img_url": task.place_img_url,
                        "name_of_location": task.name_of_location
                    }
                    task_list.append(task_list_context)
                boyn = ""
                if task_saved == "1":
                    boyn = "boy"
                elif task_saved == "2":
                    boyn = "boy boy1"
                elif task_saved == "3":
                    boyn = "boy boy1 boy2"
                elif task_saved == "4":
                    boyn = "boy boy1 boy2 boy3"
                elif task_saved == "5":
                    boyn = "boy boy1 boy2 boy3 boy4"
                messages.warning(request, 'Welcome to your adventures')
                context = {
                    "boyn" : boyn,
                    "tasks" : task_list,
                    "number_of_task" : len(tasks)

                }
                return render(request, 'map/map.html', context)
            else:
                messages.warning(request, 'Select your adventure to continue.')
                return HttpResponseRedirect('/profile')
    else:
        messages.warning(request, 'Please sign in')
        return HttpResponseRedirect(reverse('coreapp:home'))


def beginingstory(request):
    """
    This function takes user to a infromational page which gives details of specific
    adventure and only displays once when users first begin the adventure.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.

    Returns
    -------
    HttpResponseRedirectObject or HttpResponseObject
        It returns HttpResponseRedirectObject when user is currently playing this adventure.
        It returns HttpResponseObject when user is first time playing this adventure
    """
    user = request.user
    adventureid = request.GET.get('adventureid', '')
    Current_adventures = current_adventures.objects.filter(user = user)

    if Current_adventures:
        current_adventure = Current_adventures.filter(adventure_saved = adventureid)
        if current_adventure:
            game_saved = user.game_saved
            game_saved.adventure_saved = current_adventure[0].adventure_saved
            game_saved.task_saved = current_adventure[0].task_saved
            game_saved.save()
            return HttpResponseRedirect(reverse('map:map'))
        else:
            adventure = Adventure.objects.get(adventure_id = adventureid)
            Adventures_info = adventures_info.objects.get(adventure_name = adventure)
            context = {
                "adventure_title" : adventure.adventure_name,
                "items_needed" : Adventures_info.items_needed,
                "expenses" : Adventures_info.expenses,
                "locations" : Adventures_info.locations,
                "map_address" : Adventures_info.map_address,
                "adventureid" : adventureid,
                "theme_character_url" : str(adventure.theme_character_url),
                "adventure_description" : adventure.adventure_description
            }

            return render(request, 'map/details.html',context)

    else:
        adventure = Adventure.objects.get(adventure_id = adventureid)
        Adventures_info = adventures_info.objects.get(adventure_name = adventure)
        context = {
            "adventure_title" : adventure.adventure_name,
            "items_needed" : Adventures_info.items_needed,
            "expenses" : Adventures_info.expenses,
            "locations" : Adventures_info.locations,
            "map_address" : Adventures_info.map_address,
            "adventureid" : adventureid,
            "theme_character_url" : str(adventure.theme_character_url),
            "adventure_description" : adventure.adventure_description
        }

        return render(request, 'map/details.html',context)

def visitorview(request):
    """
    This function is triggered when user hit the adventure shown on homepage,
    which is showing user the adventures' detail even a user is not logged in.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.

    Returns
    -------
    HttpResponseObject
        It always returns HttoResponseObject along with a list of context dictionary
        collected from user.
    """
    adventureid = request.GET.get('adventureid', '')

    adventure = Adventure.objects.get(adventure_id = adventureid)
    Adventures_info = adventures_info.objects.get(adventure_name = adventure)
    context = {
        "adventure_title" : adventure.adventure_name,
        "items_needed" : Adventures_info.items_needed,
        "expenses" : Adventures_info.expenses,
        "locations" : Adventures_info.locations,
        "map_address" : Adventures_info.map_address,
        "adventureid" : adventureid,
        "theme_character_url" : str(adventure.theme_character_url),
        "adventure_description" : adventure.adventure_description
    }

    return render(request, 'map/visitorview.html',context)


def save_current(request):
    """
    This function is triggered when a user decides to play a specific adventure
    and hits the button at the bottom of the detail.html. This update a user's
    information in database(e.g. save which adventure he/she is playing).

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.

    Returns
    -------
    HttpResponseRedirectObject
        It always returns HttoResponseRedirectObject, it redirects user to map page.
    """
    adventureid = request.GET.get('adventureid', '')
    user = request.user
    game_saved = user.game_saved
    game_saved.adventure_saved = adventureid
    game_saved.task_saved = '1'
    game_saved.save()
    current_adventures.objects.create(user=user, adventure_saved=adventureid, task_saved='1')

    return HttpResponseRedirect(reverse('map:map'))


def task(request):
    """
    This function retrives tasks from database and displays on task pages for users to complete.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.

    Returns
    -------
    HttpResponseObject
        It always returns HttoResponseObjects along with a list of context dictionary
        collected from task information in database.
    """

    user = request.user
    game_saved = user.game_saved
    adventure_saved = game_saved.adventure_saved
    task_saved = game_saved.task_saved
    adv = Adventure.objects.get(adventure_id=adventure_saved) #needed to get from adv
    adv_name = adv.adventure_name
    task = adv.task_set.get(adventure_name=adv, task_number=task_saved)

    task_detail = task.task_detail
    task_ans = task.task_ans
    task_type = str(task.task_type)
    task_description = task.task_description
    show_textbox = ''
    if task_type == 'Questions':
        show_textbox = "show"

    context = {
        'show_textbox' : show_textbox,
        'adv_id' : adventure_saved,
        'adv_name' : adv_name,
        'task_num' : task_saved,
        'task_detail' : task_detail,
        'task_ans' : task_ans,
        "task_description" : task_description,
    }

    return render(request, 'map/taskpage.html', context)


def mission_task_submission(request):
    """
    This function updates user's current progress of the specific adventure(e.g. a user completes a task).

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.

    Returns
    -------
    HttpResponseRedirectObject or HttoResponseObjects
        It returns HttoResponseRedirectObjects, it redirects a user to next task when he completes one.

adventure_game/map/templates/map/adventure_completion.html
{% extends "coreapp/base.html" %}
{% load staticfiles %}
{% block map_css_js %}
<link rel="stylesheet" type="text/css" href="{% static "map/css/task.css" %}">

{% endblock %}



{% block content %}
<div class = "container section">
<div row class="congratulate">
  <h1>Congratulations, you have completed the adventure!!!</h1>
  <div class ="text-center">
    <a href="/profile">
      <button class="btn btn-danger btn-lg return">Return to your profile!</button>
    </a>
  </div>
</div>
</div>
{% endblock %}

adventure_game/map/templates/map/details.html
{% extends "map/task_base.html" %}
{% load staticfiles %}
{% block title %}Task 1{% endblock %}
{% block map_css_js %}
<link rel="stylesheet" type="text/css" href={% static "map/css/task.css" %}>

{% endblock %}

{% block content %}
<div class="container">

      <div class="page-header">
        <h1>{{ adventure_title }}</h1>
        <p class="lead">{{ adventure_description }}</p>
      </div>
      {% autoescape off %}


      <h3 style="color: red;">Items needed:</h3>
      <p style="font-size: 1.5em;">{{ items_needed }}</p>

      <h3 style="color: red;">Expenses:</h3>
      <p style="font-size: 1.5em;">{{ expenses }}</p>

      <h3 style="color: red;">Locations:</h3>
      <p style="font-size: 1.5em;font-family:Monaco, monospace;">{{ locations }}</p>

      {% endautoescape %}
    </div>

    <iframe style="margin-left: 50px;" src="{{ map_address }}" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
    <img style="width:400px;float:right;margin-right: 100px;" src="{{ theme_character_url }}" class="img-responsive">

    <form class="save_current" action="/adventure/save_current" method="get">
    <input type="hidden" name="adventureid" value="{{ adventureid }}">
    <input class="btn btn-block btn-lg btn-primary" type="submit" value="{{ adventure_title }}"><br>
    </form>
{% endblock %}

adventure_game/map/templates/map/index.html
{% extends "coreapp/base.html" %}
{% load staticfiles %}
{% block title %}Adventure Map{% endblock %}
{% block map_css_js %}
<link rel="stylesheet" type="text/css" href={% static "map/css/style.css" %}>

{% endblock %}

{% block content %}


      <div id="space"></div>
      <div>

      <!-- <canvas id="girl" style="border:1px solid #000000;"></canvas> -->
      <canvas id="boy" class="{{ boyn }}"></canvas>
      <canvas id="env"></canvas>


      <img id="empire" src={% static "map/images/buildings/Empire_State_Building.png" %}>
      <img id="statue_liberty" src={% static "map/images/buildings/statue_liberty.png" %}>
      <img id="metropolitan" src={% static "map/images/buildings/metropolitan.png" %}>
      <img id="grand" src={% static "map/images/buildings/grand.png" %}>
      <img id="central" src={% static "map/images/buildings/central.png" %}>

      {% if image1 %}
      {% autoescape off %}
      {{ image1 }}
      {% endautoescape %}
      {% endif %}
      <!-- <img src="https://i.kinja-img.com/gawker-media/image/upload/en4oskk7fjw1dm0dczaj.jpg" /> -->
      <div id="grand_title" class="building_name">Grand Central Terminal</div>
      <div id="empire_title" class="building_name">Empire State Building</div>
      <div id="central_title" class="building_name">Central Park</div>
      <div id="statue_title" class="building_name">Statue of Liberty</div>
      <div id="metropolitan_title" class="building_name">The Metropolitan Museum of Art</div>

      <a href="{% url 'map:task1' %}"><img id="number1" class="number_mission" src={% static "map/images/numbers/number1.png" %}></a>
      <a href="{% url 'map:task2' %}"><img id="number2" class="number_mission" src={% static "map/images/numbers/number2.png" %}></a>
      <a href=""><img id="number3" class="number_mission" src={% static "map/images/numbers/number3.png" %}></a>
      <a href=""><img id="number4" class="number_mission" src={% static "map/images/numbers/number4.png" %}></a>
      <a href=""><img id="number5" class="number_mission" src={% static "map/images/numbers/number5.png" %}></a>
      <!-- <img id="mist" src="static/images/mist/mist.png"> -->
      <img id="path1" src={% static "map/images/path1.png" %}>
      <img id="path2" src={% static "map/images/path1.png" %}>
      <img id="path3" src={% static "map/images/path1.png" %}>
      <img id="path4" src={% static "map/images/path1.png" %}>

      <!-- <img class="question_mark first question_mark1" src={% static "map/images/question_mark.png"%}>
      <img class="question_mark first question_mark2" src={% static "map/images/question_mark.png"%}>
      <img class="question_mark first question_mark3" src={% static "map/images/question_mark.png"%}>
      <img class="question_mark first question_mark4" src={% static "map/images/question_mark.png"%}>
      <img class="question_mark first question_mark5" src={% static "map/images/question_mark.png"%}> -->

      <img id="tree1" src={% static "map/images/env/tree1.png" %}>
      <img id="tree2" src={% static "map/images/env/tree2.png" %}>
      <img id="tree3" src={% static "map/images/env/tree3.png" %}>

      <img id="hamster" src={% static "map/images/env/hamster.png" %}>
      <img id="dog" src={% static "map/images/env/dog.png" %}>
      <img id="monster" src={% static "map/images/env/monster.png" %}>


      <!-- <img id="daddy" class="parent" src={% static "map/images/characters/daddy1.png" %}>
      <img id="girl" src={% static "map/images/characters/girl1.png" %}>
      <img id="mom" class="parent" src={% static "map/images/characters/mom1.png" %}> -->
      </div>


<script src={% static "map/js/sprite.js" %}></script>

{% endblock %}

adventure_game/map/templates/map/task_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parent &amp; Child Adventure Game - {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="http://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href={% static "css/stylesheet.css" %} rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/x-icon" href="https://vignette2.wikia.nocookie.net/finalfantasy/images/a/ad/BlackWizard-ff1-psp.png/revision/latest?cb=20110503073352">
    <script type="text/javascript" src={% static "js/home.js" %}></script>
    {% block map_css_js %}{% endblock %}

    <!-- <link rel="stylesheet" type="text/css" href="static/bootstrap-3.3.5-dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="static/bootstrap-3.3.5-dist/css/bootstrap-theme.min.css"> -->
  	<!-- <script src="static/bootstrap-3.3.5-dist/js/bootstrap.min.js"></script> -->
</head>
<body>
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'coreapp:home' %}"><span>Adventure Game</span></a>
      </div>
    {% if user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{% url 'coreapp:individual' %}">My Adventures</a>
          </li>
          <li>
            <a href="{% url 'coreapp:profile' %}">Profile</a>
          </li>
          <li >
            <a href="{% url 'coreapp:logout' %}">Log Out</a>
          </li>
        </ul>
      </div>
    {% else %}
      <div class="collapse navbar-collapse" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="page-scroll">
            <a href="{% url 'coreapp:home' %}#adventures">Adventures</a>
          </li>
          <li class="page-scroll">
            <a href="{% url 'coreapp:home' %}#about">About</a>
          </li>
          <li class="page-scroll">
            <a href="{% url 'coreapp:home' %}#contact">Contact</a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In</a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
              <form action="{% url 'coreapp:auth' %}" method="post" accept-charset="UTF-8">
                {% csrf_token %}
                <input id="user_username" type="text" name="username" size="30">
                <input id="user_password" type="password" name="password" size="30">
                <input id="user_remember_me" type="checkbox" name="remember_Me" value="1">
                <label class="string optional" for="user_remember_me">Remember me</label>
                <input class="btn btn-primary signin-btn" type="submit" name="commit" value="Sign In">
                <div  class = "register-link">
                  <a href="{% url 'coreapp:registration' %}">Register</a>
                </div>
              </form>
            </div>
          </li>
        </ul>
      </div>
  {% endif %}
    </div>
  </div>


{% if messages %}
  {% for message in messages %}

    <div id="alertmessage" class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>{{ message }}
    </div>
    <script>
    window.setTimeout(function() {
      $("#alertmessage").fadeOut(700);
    }, 2500);

    </script>
  {% endfor %}
{% endif %}

	{% block content %}{% endblock %}

</body>
</html>

adventure_game/map/templates/map/taskpage.html
{% extends "coreapp/base.html" %}
{% load staticfiles %}
{% block map_css_js %}
<link rel="stylesheet" type="text/css" href="{% static "map/css/task.css" %}">
<link href="{% static "map/css/scramble.css" %}" rel="stylesheet">
{% endblock %}



{% block content %}
<div class="section">
<div class="container">
      <div class="row">
        <div class="col-lg-12">

            <img class="hamster_head1" src="http://cliparts.co/cliparts/di9/Bg6/di9Bg6Ai7.png" />
            <img class="hamster_head2 img-responsive" src="http://www.misskatecuttables.com/uploads/shopping_cart/9493/large_cute-witch.png" />
            <h1 id="adventure_title">{{ adv_name }}</h1>

            <br><br><br><br><br><br>
            <h3 id="task_num">You are at task: {{ task_num }}</h3>
            <br>
            <div>{{ task_description }}</div>
            <br><br><br>

          {% autoescape off %}

          <p><span style="font-size:1.4em;">Your task : </span><span  style="color:red;">{{ task_detail }}</span></p>

          {% endautoescape %}
          <br>

          <div id="scramble" class=""></div>
          <div id="game"></div>
          </p>
        </div>
      </div>




      {% if show_textbox %}
      <p>The answer for this task is :{{ task_ans }}
        <form action="{% url 'map:questionstasksubmission' %}" method="get" id="nexttask1">
              <input type="text" class = "result-textarea"name="task_ans" placeholder="Enter you result here">
              <br>
              <button type="submit" class="btn btn-info next-task">Next Task</button>
        </form>
      {% else %}
        <form action="{% url 'map:missiontasksubmission' %}" method="get" id="nexttask2">
              <button type="submit" class="btn btn-info next-task">Next Task</button>
        </form>
      {% endif %}
        <form action="{% url 'map:map' %}" method="POST" id="BackToMap"> {%csrf_token %}
              <button type="submit" class="btn btn-info go-back">Go Back to Map</button>
        </form>
</div>
</div>
<!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
<script type="text/javascript" src="{% static "map/js/scramble.js" %}"></script>
<script type="text/javascript" src="{% static "map/js/task.js" %}"></script>




{% endblock %}

adventure_game/map/templates/map/visitorview.html
{% extends "map/task_base.html" %}
{% load staticfiles %}
{% block title %}Task 1{% endblock %}
{% block map_css_js %}
<link rel="stylesheet" type="text/css" href={% static "map/css/task.css" %}>

{% endblock %}

{% block content %}
<div class="container">

      <div class="page-header">
        <h1>{{ adventure_title }}</h1>
        <p class="lead">{{ adventure_description }}</p>
      </div>
      {% autoescape off %}
      <h3 style="color: red;">Items needed:</h3>
      <p style="font-size: 1.5em;">{{ items_needed }}</p>

      <h3 style="color: red;">Expenses:</h3>
      <p style="font-size: 1.5em;">{{ expenses }}</p>

      <h3 style="color: red;">Locations:</h3>
      <p style="font-size: 1.5em;font-family:Monaco, monospace;">{{ locations }}</p>
      {% endautoescape %}

    </div>
    <iframe style="margin-left: 50px;" src="{{ map_address }}" width="500" height="350" frameborder="0" style="border:0" allowfullscreen></iframe>
    <img style="width:400px;float:right;margin-right: 100px;" src="{{ theme_character_url }}" class="img-responsive"><br><br>
    <div class="container">
    <a href="{% url 'coreapp:registration' %}"> <span style="text-decoration: underline; color:black; font-size:20px">Want to play? Join with us today!!</span></a>
  </div><br><br>
{% endblock %}