adventure_game/adventure_game/urls.py
"""This module is used to route the urls to the views
"""

from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('coreapp.urls', namespace="coreapp")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^adventure\d*/', include('map.urls', namespace="map")),
]

adventure_game/coreapp/urls.py
#pylint: disable=C0103
from django.conf.urls import url
from coreapp import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^auth/$', views.auth_view, name='auth'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^register/$', views.registration, name='registration'),
    url(r'^registration-submission/$', views.registration_submission, name='registrationSubmission'),
    url(r'^profile/$', views.profile, name='profile'),
    url(r'^individual/$', views.individual, name="individual"),
    url(r'^story/$', views.story, name='story'),
    url(r'^add-family-member-submission/$', views.add_family_member_submission, name="addFamilySubmission"),
    url(r'^add-family-member/$', views.add_family_member, name="add-family-member"),
    url(r'^get_adventure_detail/$', views.get_adventure_detail, name='get_adventure_detail'),
    url(r'^adventureslist$', views.adventureslist, name="adventureslist"),
    url(r'^contact$', views.contact, name="contact"),
]

adventure_game/map/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.map, name='map'),
    url(r'^beginingstory$', views.beginingstory, name="beginingstory"),
    url(r'^task\d*$', views.task, name="task"),
    url(r'^missiontasksubmission$', views.mission_task_submission, name="missiontasksubmission"),
    url(r'^questionstasksubmission$', views.questions_task_submission, name="questionstasksubmission"),
    url(r'^save_current/$', views.save_current, name="save_current"),
    url(r'^special_game_json/$', views.special_game_json, name="special_game_json"),
    url(r'^visitorview$', views.visitorview, name="visitorview"),
]

adventure_game/coreapp/models.py
"""This module contains all the models representing the data in the database.
"""
from django.db import models
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    def __unicode__(self):
        return u'Profile of user: %s' % self.user.username

class Character(models.Model):
    """
    This holds family members in database.
    A family member has a name and pin number that
    need to go to their own profile page.
    """
    user = models.ForeignKey(User)
    character_name = models.CharField(max_length=200)
    character_pin = models.CharField(max_length=200, null=True)
    is_logged = models.BooleanField(default=False)

    def __str__(self):
        return self.character_name

class Level_num(models.Model):
    """
    Each user has game points which can be gained from our games.
    A user's level is determined by their points.
    """
    user = models.OneToOneField(User)
    user_point = models.PositiveIntegerField(default=0)
    user_level_choices = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    )
    user_level = models.IntegerField(choices=user_level_choices, default='1')

    def __unicode__(self):
        return str(self.user_level)


class Track(models.Model):
    """
    This holds a list of adventures that a user has completed.
    """
    user = models.ForeignKey(User)
    adventure_done = models.CharField(max_length=10, blank=True, default='')

    def __unicode__(self):
        return self.adventure_done


class Game_saved(models.Model):
    """
    This saves the progress of a game.
    """
    user = models.OneToOneField(User)
    adventure_saved = models.CharField(max_length=10, blank=True, default='')  #adventure_id
    task_saved = models.CharField(max_length=10, blank=True, default='')   #task_number

    def __unicode__(self):
        return 'Last saved at adventure id#'+str(self.adventure_saved) + 'task #:' + str(self.task_saved)

class current_adventures(models.Model):
    """
    This saves users' adventures that are currently played.
    """
    user = models.ForeignKey(User)
    adventure_saved = models.CharField(max_length=10, blank=True, default='')  #adventure_id
    task_saved = models.CharField(max_length=10, blank=True, default='')   #task_number

    def __unicode__(self):
        return 'saved adventure id#'+str(self.adventure_saved) + 'task #:' + str(self.task_saved)

class ContactUs(models.Model):
    name = models.CharField(max_length=20)
    email = models.EmailField(max_length=254)
    msg = models.TextField(max_length=2000)

adventure_game/coreapp/views.py
""" This module handles the user registration, login, family member creation,
and also has the home page view.
"""
from django.shortcuts import render
from django.http import HttpResponseRedirect, JsonResponse
from django.contrib import auth, messages
from django.core.exceptions import PermissionDenied
from django.template.context_processors import csrf #user security
from django.contrib.auth.models import User
from django.template import RequestContext
from .models import Level_num, Game_saved, ContactUs, current_adventures
from .queries import get_logged_in_char, get_all_characters
from .utilities import  get_profile_context, get_adventure_info
from map.models import adventures_info, Adventure, Task


def home(request):
    """This is the home view. It is called when the user goes to the '/' route.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.


    Returns
    -------
    HttpResponseObject
        Combines a given template with a given context dictionary and renders the template.
    """
    user = request.user
    context = get_adventure_info()
    context.update(csrf(request))
    return render(
        request,
        'coreapp/home.html',
        context=context)

def adventureslist(request):
    """This is the adventures list view. It is called when the user goes to the '/adventureslist/' route.
    This page lists all of our adventures

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.


    Returns
    -------
    HttpResponseObject
        Combines a given template with a given context dictionary and renders the template.
    """
    user = request.user
    context = get_adventure_info()

    return render(request, 'coreapp/adventureslist.html',context)

def contact(request):
    """This is the contact view. User reaches this view when he hits the
    send button on the Contact Us form in home page.

    When a visitor fills out the Contact Us
    form and hits the send button in home page, the information is posted to this view which pushes
    to database for admin to view.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.


    Returns
    -------
    HttpResponseRedirectObject
        Redirects the user to the '/' route after the message is submitted.
    """
    name = request.POST.get('name', '')
    email = request.POST.get('email', '')
    msg = request.POST.get('msg', '')
    ContactUs.objects.create(name=name, email=email, msg=msg)
    messages.success(request, 'Submitted, Thank you!')
    return HttpResponseRedirect('/')

def profile(request):
    """This is the profile view. It is called when the user goes to the '/profile/' route.

    If the user hasn't logged into a char yet, the view renders the individual.html template,
    with a context dictionary created by the function get_profile_context. Otherwise,
    the view will be rendered with a context dictionary that contains the names of all
    the family members attached to the user account as well as the user's last name.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.


    Returns
    -------
    HttpResponseObject
        Combines a given template with a given context dictionary and renders the template.
    """
    user = request.user
    characters = get_all_characters(user)
    if get_logged_in_char(characters):
        context = get_profile_context(user, characters)
        return render(request, 'coreapp/individual.html', context)
    else:
        family_members = characters
        userlname = user.last_name
        context = {'family_members' : family_members,
                   'lastname' : userlname,
                  }
        return render(request, 'coreapp/profile.html', context)

def story(request):
    """This is the story view. It is called when the user goes to the '/story' route.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.


    Returns
    -------
    HttpResponseObject
        Combines a given template with a given context dictionary and renders
        the story.html template.
    """
    return render(request, 'coreapp/story.html')

def auth_view(request):
    """This is the story view. It handles user login authentication.

    If credentials are correct, the user is logged in
    and a message is shown confirming user logged in. If account was banned, message
    is shown message telling them account is banned. If credentials are invalid, user is
    told credential is invalid."If credentials are correct, the user is logged in
    and a message is shown confirming user logged in. If account was banned, message
    is shown message telling them account is banned. If credentials are invalid, user is
    told credential is invalid.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.


    Returns
    -------
    HttpResponseRedirectObject
        Redirects the user to '/' route.
    """

    username = request.POST.get('username', '')
    password = request.POST.get('password', '')
    user = auth.authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            auth.login(request, user)
            messages.success(request, 'Hi %s, you have successfully logged in.' %(user.last_name))
            return HttpResponseRedirect('/')
        else:
            messages.success(request, 'Your account has been banned,' \
                             ' please contact us to re-activate your account!')
            return HttpResponseRedirect('/')
    else:
        messages.success(request, 'The account you entered is invalid, please try again!')
        return HttpResponseRedirect('/')

def logout(request):
    """This is the logout view. It is called when the user hits the logout button.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.


    Returns
    -------
    HttpResponseRedirectObject
        Logs the user out, redirects the user to the '/' view and displays a message
        telling the user they have succesfully logged out.
    """
    auth.logout(request)
    messages.success(request, 'You have successfully logged out.')
    return HttpResponseRedirect('/')

def registration_submission(request):
    """This is the registration submission view.

    When the user fills out the registration
    form and hits the submit button, the information is posted to this view which creates
    an account for the user with the credentials in the form. Adventure progress is also created.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.

    Returns
    -------
    HttpResponseRedirectObject
        Redirects the user to the '/' route after user is created.
    """
    username = request.POST.get('username', '')
    firstname = request.POST.get('firstname', '')
    lastname = request.POST.get('lastname', '')
    email = request.POST.get('email', '')
    password = request.POST.get('password', '')
    if len(User.objects.filter(username=username)) != 0: #pylint: disable=E1101
        return registration(request, "Try again, the username %s %s."
                            % (username, "is already taken"))
    if len(User.objects.filter(email=email)) != 0: #pylint: disable=E1101
        return registration(request, "Try again, %s %s."
                            % ("there is already an account with that email", email))
    user = User.objects.create_user(username=username, email=email, password=password,
                                    first_name=firstname, last_name=lastname) #pylint: disable=E1101
    first_char = user.character_set.create(character_name="pin#1111", character_pin="1111")
    first_char.is_logged = True
    first_char.save()
    Level_num.objects.create(user=user, user_point=0, user_level=1)
    Game_saved.objects.create(user=user, adventure_saved="", task_saved="")
    user = auth.authenticate(username=username, password=password)
    auth.login(request, user)
    return HttpResponseRedirect('/')

def registration(request, message=None):
    """This is the registration view. User reaches this view when he hits the
    register button on the login form.

    Parameters
    ----------
    request: HttpRequestObject
        Django request object that contains a variety of information from the middlewares.

    message: String
        A message that can be passed from one view to another. Used to display incorrect
        credential submission.

    Returns
    -------
    HttpResponseObject
        Combines the registration template with a given context dictionary and renders the template.
    """
    context = {}
    context.update(csrf(request))
    if message is not None:
        context['message'] = message
    return render(request, 'auth/registration.html', context)

def add_family_member(request, message=None):
    """This is the view for adding a family member. Renders a form for users to
    fill out to add the family member.

    Parameters
    ----------
    request: HttpRequest
        Django request object that contains a variety of information from the middlewares.

    message: String
        A message that can be passed from one view to another. Used to display incorrect
        credential submission.

    Returns
    -------
    HttpResponseObject

adventure_game/coreapp/templates/coreapp/adventureslist.html
{% extends "coreapp/base.html" %}
{% block title %} List {% endblock %}
{% load staticfiles %}
{% block content %}

<div class="container marketing">


  {% for x, y, z, u in zipped %}

  <!-- START THE FEATURETTES -->

  <hr class="featurette-divider">

  <div class="row featurette">
    <div class="col-md-7">
      <h2 class="featurette-heading">{{ y }}</h2>
      <p class="lead">{{ u }}</p>
    </div>
    <div class="col-md-5">
      <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="{{ x }}" data-holder-rendered="true">
    </div>
  </div>
  {% if user.is_authenticated %}
  <form class="adventureform" action="/adventure/beginingstory" method="get">
  <input type="hidden" name="adventureid" value="{{ z }}">
  <input class="tobedeleted btn btn-info" id="play" type="submit" value="Play it!"><br>
  </form>
  {% else %}
  <form class="adventureform" action="{% url 'coreapp:registration' %}" method="get">
  <input class="tobedeleted btn btn-info" id="play" type="submit" value="Join to play!"><br>
  </form>
  {% endif %}

  {% endfor %}
  <br>
</div>

{% endblock %}

adventure_game/coreapp/templates/coreapp/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Parent &amp; Child Adventure Game - {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js"></script>
    <script type="text/javascript" src="https://netdna.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.5/flatly/bootstrap.min.css" rel="stylesheet" type="text/css">
    <link href={% static "css/stylesheet.css" %} rel="stylesheet" type="text/css">
    <link rel="shortcut icon" type="image/x-icon" href="https://vignette2.wikia.nocookie.net/finalfantasy/images/a/ad/BlackWizard-ff1-psp.png/revision/latest?cb=20110503073352">
    <script type="text/javascript" src={% static "js/home.js" %}></script>
    {% block map_css_js %}{% endblock %}

    <!-- <link rel="stylesheet" type="text/css" href="static/bootstrap-3.3.5-dist/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="static/bootstrap-3.3.5-dist/css/bootstrap-theme.min.css"> -->
  	<!-- <script src="static/bootstrap-3.3.5-dist/js/bootstrap.min.js"></script> -->
</head>
<body>
  <div class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header page-scroll">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-ex-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'coreapp:home' %}"><span>Adventure Game</span></a>
      </div>
    {% if user.is_authenticated %}
      <div class="collapse navbar-collapse" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li>
            <a href="{% url 'map:map' %}">My Adventures</a>
          </li>
          <li>
            <a id="profile" href="{% url 'coreapp:profile' %}">Profile</a>
            {% if islogged %}

        		<script>
        		$(document).ready(function(){
        			$("#profile").text("{{ islogged }}");
        		});
        		</script>

        		{% endif %}
          </li>
          <li >
            <a href="{% url 'coreapp:logout' %}">Log Out</a>
          </li>
        </ul>
      </div>
    {% else %}
      <div class="collapse navbar-collapse" id="navbar-ex-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li class="page-scroll">
            <a href="{% url 'coreapp:home' %}#adventures">Adventures</a>
          </li>
          <li class="page-scroll">
            <a href="{% url 'coreapp:home' %}#about">About</a>
          </li>
          <li class="page-scroll">
            <a href="{% url 'coreapp:home' %}#contact">Contact</a>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign In</a>
            <div class="dropdown-menu" style="padding: 15px; padding-bottom: 0px;">
              <form action="{% url 'coreapp:auth' %}" method="post" accept-charset="UTF-8">
                {% csrf_token %}
                <input id="user_username" type="text" name="username" size="30">
                <input id="user_password" type="password" name="password" size="30">
                <input id="user_remember_me" type="checkbox" name="remember_Me" value="1">
                <label class="string optional" for="user_remember_me">Remember me</label>
                <input class="btn btn-primary signin-btn" type="submit" name="commit" value="Sign In">
                <div  class = "register-link">
                  <a href="{% url 'coreapp:registration' %}">Register</a>
                </div>
              </form>
            </div>
          </li>
        </ul>
      </div>
  {% endif %}
    </div>
  </div>

<!-- {% if alertmessage %}
<div id="alertmessage">
<div class="alert alert-success fade in">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>{{ alertmessage }}
</div>
</div>
{% endif %} -->

{% if messages %}
  {% for message in messages %}

    <div id="alertmessage" class="alert alert-success fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>{{ message }}
    </div>
    <script>
    window.setTimeout(function() {
      $("#alertmessage").fadeOut(1000);
    }, 5000);

    </script>
  {% endfor %}
{% endif %}

	{% block content %}{% endblock %}

</body>

<div class="wrapper">
<footer class="footer-above">
  <div class="container">
    <div class="row">
      <div class="footer-col col-lg-12 text-center">
        <h3>Socia Media</h3>
        <ul class="list-inline">
          <li>
            <a href="#" class="btn-social btn-outline">
              <i class="fa fa-fw fa-facebook"></i>
            </a>
          </li>
          <li>
            <a href="#" class="btn-social btn-outline">
              <i class="fa fa-fw fa-google-plus"></i>
            </a>
          </li>
          <li>
            <a href="#" class="btn-social btn-outline">
              <i class="fa fa-fw fa-twitter"></i>
            </a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<footer class="footer-below">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        Copyright © 2015
      </div>
    </div>
  </div>
</footer>
</div>
</html>

adventure_game/coreapp/templates/coreapp/home.html
{% extends "coreapp/base.html" %}
{% load staticfiles %}
{% block title %}Home{% endblock %}
{% block content %}
<header>
    <div class="container">
      <div class="row">
        <div class="col-lg-12">
          <!-- TODO remove the style and put into css -->
          <img class="center-block img-responsive" src="http://i.imgur.com/uci2Csw.png" style="max-width: 30%;" alt="wizard">
          <span class="name">Adventure Game</span>
          <span class="description">Spend some time with your children!</span>
        </div>
      </div>
    </div>
  </header>
  <section id="adventures">
    <div class="container">
      <div class="col-lg-12 text-center">
        <h2>Check out our adventures!</h2>
        <hr class="dark"/>
      </div>
      <div class="row">
        {% for w, x, y, z in zipped %}
        <div class="col-sm-4 adventure-item">

          {% if user.is_authenticated %}
          <form class="adventureform" action="/adventure/beginingstory" method="get">
          <input type="hidden" name="adventureid" value="{{ y }}">
          <input style="width:700px;height:250px;" class="img-responsive" id="play" type="image" src="{{ w }}"> {{ x }}
          </form>

          {% else %}
          <form class="adventureform" action="/adventure/visitorview" method="get">
          <input type="hidden" name="adventureid" value="{{ y }}">
          <input style="width:700px;height:250px;" class="img-responsive" id="play" type="image" src="{{ w }}"> {{ x }}
          </form>
          {% endif %}
          </div>
          {% endfor %}
          <div class="col-sm-4 adventure-item">
            <a href="{% url 'coreapp:adventureslist' %}">
            <img id="more" class="img-responsive" src="http://static1.squarespace.com/static/542c91d6e4b0192f92c6fd5a/55a2f8a3e4b022eb02879698/55a2f8a3e4b0bb17f7b37465/1436743844227/thumb_more-coming-soon.jpg" style="width:700px;height:250px;"></a>
            Check out for more...
          </div>

      </div>
    </section>
    <section id="about">
      <div class="container">
        <div class="col-lg-12 text-center">
          <h2>About</h2>
          <hr class="light"/>
          <div class="col-lg-4 col-lg-offset-2">
            <p>Our Adventure Games are deisgned to bring families together in a way that suits the soceity of today. Through technology families will get to work as a team to experience exciting stories and learn about each other along the way. </p>
          </div>
          <div class="col-lg-4">
            <p>The adventures here are not just designed to entertain the younger members of the family, but are equally engaging for those of all ages.</p>
          </div>
        </div>
      </div>
    </section>
    <section id="contact">
      <div class="container">
        <div class="col-lg-12 text-center">
         <h2>Contact Us</h2>
         <hr class="dark"/>
       </div>
       <div class="row">
        <div class="col-lg-8 col-lg-offset-2">
         <form role="form" action="{% url 'coreapp:contact' %}" method="post"> {% csrf_token %}
          <div class="row">
            <div class="form-group col-xs-12 floating-label-form-group">
              <label for="name">Name</label>
              <input class="form-control" type="text" name="name" placeholder="Name">
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12 floating-label-form-group">
              <label for="email">Email Address</label>
              <input class="form-control" type="email" name="email" placeholder="Email Address">
            </div>
          </div>
          <div class="row">
            <div class="form-group col-xs-12 floating-label-form-group">
              <label for="message">Message</label>
              <textarea placeholder="Message" class="form-control" rows="5" name="msg"></textarea>
              <!-- <input class="form-control" type="text" name="msg" placeholder="Email Address"> -->
            </div>
          </div>
          <br>
          <div class="row">
            <div class="form-group col-xs-12">
              <button type="submit" class="btn btn-lg btn-info" style="background-color:#2BAACF">Send</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
<script type="text/javascript" src={% static "js/home.js" %}></script>


{% endblock %}

adventure_game/coreapp/templates/coreapp/individual.html
{% extends "coreapp/base.html" %}
{% block title %} Individual {% endblock %}
{% load staticfiles %}
{% block content %}



		<div class="fb-profile">
			<img align="left" class="fb-image-lg" src="http://lorempixel.com/850/280/nightlife/5/" alt="Profile image example"/>
			<img align="left" class="fb-image-profile thumbnail" src="http://i.imgur.com/yA1HtnV.png" alt="Profile image"/>
			<div class="fb-profile-text">
				<h1>Hi, {{ character_name }}! </h1>
				<h8>
					<a style="color: #0654ba;" href="/individual/">(Add more family members?)</a>
				</h8>
				<br>
				<br>
					<p>Level: {{ level }}
						{% for l in rangelist %}
						<img style="width:3%;" src="http://images.clipartpanda.com/medal-clipart-Gold_Medal_2_Vector_Clipart.png">
						{% endfor %}
					</p>
				<div style="width:40%;height:25px;" class="progress">
  			<div class="progress-bar" role="progressbar" aria-valuenow="{{ exp }}" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em;padding-top:7px;font-size:1em;width:{{ exp }}%">
    		{{ exp }}%
  			</div>
</div>
			</div>
		</div>
 <!-- /container -->

	<!-- <div class="container"> -->
		<!-- <p>Check out our adventures:  </p>
		<div class="row">
			<div class="col-lg-12">
				<a href="/story/">
					<img src={% static "img/park.jpg" %} class ="park img-responsive"/>
					<span class ="park-text">Help the Wizard!</span>
				</a>
			</div>
		</div>
		<br> -->


		<br><br><br><br>


		<div class="container marketing">


			{% for x, y, z, u, q, w in zipped %}

      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">{{ y }}</h2>
          <p class="lead">{{ u }}</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="500x500" src="{{ x }}" data-holder-rendered="true">
        </div>
      </div>
			<form class="adventureform" action="/adventure/beginingstory" method="get">
			<input type="hidden" name="adventureid" value="{{ z }}">
			{% if q and w %}
			<p style="color:red;">You have completed this adventure, but you can replay it if you want.</p>
			<p style="color:red;">(Previous record will be deleted)</p>
			<input class="btn btn-info" id="continue" type="submit" value="Replay"><br>
			{% elif q %}
			<input class="btn btn-info" id="continue" type="submit" value="Continue your adventure"><br>
			{% else %}
			<input class="btn btn-info" id="play" type="submit" value="Play it!"><br>
			{% endif %}
			</form>
			{% endfor %}






      <footer>
        <p class="pull-right"><a href="#">Back to top</a></p>
      </footer>

    </div>


{% endblock %}

adventure_game/coreapp/templates/coreapp/profile.html
{% extends "coreapp/base.html" %}
{% load staticfiles %}
{% block content %}
<div class ="team">
  <div class="container-fluid">
    <div class="row">
      <h2 class="text-center">Welcome the <i>{{ lastname }}</i> family!</h2>
  {% if not family_members %}
    <p class="text-center">It seems you have no family members added to your account yet!<br>
      Would you like to add one now?</p>
    <div class="container">
    <a href="{% url 'coreapp:add-family-member' %}">
      <button class="btn btn-lg btn-info btn-block add-family-btn text-center">
        Add one here!
      </button>
    </a>
    </div>
  {% else %}
    <br>
    <h5 class="text-center">Select your character below.. </h5>
    <br>

    <form action="/individual/" method="POST">


        {% for items in family_members %}
          <div class="col-md-4">
            <label>
            <img src="http://i.imgur.com/xB2zVEd.png" class="center-block img-responsive" width="285"/>
            <h3 class="text-center">
              <input type="radio" name="character_name" value =  "{{ items }}" > {{ items }}
            </h3>
          </label>
          </div>
        {% endfor %}
    </div>
  </div>
  <br>
  <h5 class="text-center"> Enter the PIN for the selected character </h5>
  <div class="container">
    <div class="row">
      <div class="col-lg-4 col-lg-offset-4 box-shadow--6p">
        <div class="panel panel-default pin-panel">
          <div class="text-center panel-body">
            <h3>Pin</h3>
            <!-- <form class="form-inline text-center" action="/individual/" method="POST"> -->
              {% csrf_token %}
              <input type="password" name="character_pin" id="pin" class="form-control" placeholder="Enter PIN To Go To Your Page">
              <br>
              <div id=button>
              <button type="submit" class="btn submit-button">To my individual page
                <i class="fa fa-arrow-right"></i>
              </button>
            </div>
            <br>
            <a class="add-family-link" href="{% url 'coreapp:add-family-member' %}">Click Here To Add More Family Members</a>

            </form>

          </div>
        </div>
      </div>
{% endif %}
    </div>
  </div>
</div>
{% endblock %}